# Generated by Django 4.2.6 on 2023-10-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(default='your_default_value_here'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(default='your_default_value_here', max_length=50),
        ),
    ]
